/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CompiledQueryPlan {
  get root(): CompiledSqlStatement
  get batches(): Array<CompiledBatchStep>
  compileBatch(name: string, keys: readonly unknown[]): CompiledSqlStatement
}

export declare class ComposedQueryGraph {
  get name(): string
  withBatchRelation(graph: RelationalQueryGraph, relation: import('./dsl.js').BatchRelationWire): ComposedQueryGraph
  compileSqlServerPlan(
    operation: import('./definition.js').QueryOperation,
    options?: import('./definition.js').SqlServerCompileOptions,
  ): CompiledQueryPlan
  compileOraclePlan(
    operation: import('./definition.js').QueryOperation,
    options?: import('./definition.js').OracleCompileOptions,
  ): CompiledQueryPlan
}

export declare class QueryGraph {
  get name(): string
  get root(): string
  get sourceCount(): number
  get relationCount(): number
  hasSource(source: string): boolean
  hasField(source: string, field: string): boolean
  hasParameter(parameter: string): boolean
  hasRelation(relation: string): boolean
  selectableFields(): Array<string>
  withRelationalMapping(mapping: import('./definition.js').RelationalMapping): RelationalQueryGraph
}

export declare class RelationalQueryGraph {
  get name(): string
  compose(): ComposedQueryGraph
  compileSqlServer(
    operation: import('./definition.js').QueryOperation,
    options?: import('./definition.js').SqlServerCompileOptions,
  ): CompiledSqlStatement
  compileOracle(
    operation: import('./definition.js').QueryOperation,
    options?: import('./definition.js').OracleCompileOptions,
  ): CompiledSqlStatement
}

export interface CompiledBatchStep {
  name: string
  parentKey: string
  childKey: string
  keyParameter: string
  parameters: Readonly<Record<string, unknown>>
  cardinality: import('./dsl.js').BatchCardinality
  parentKeyInjected: boolean
  childKeyInjected: boolean
}

export interface CompiledSqlColumn {
  name: string
  path: string
  scalarType: import('./definition.js').ScalarType
  nullable: boolean
  relations: Array<string>
}

export interface CompiledSqlRelation {
  name: string
  from: string
  to: string
  cardinality: import('./definition.js').RelationCardinality
  required: boolean
}

export interface CompiledSqlStatement {
  sql: string
  bindings: Array<SqlBinding>
  columns: Array<CompiledSqlColumn>
  relations: Array<CompiledSqlRelation>
}

export declare function registerDefinition<const Definition extends import('./definition.js').GraphDefinitionInput>(
  definition: import('./definition.js').ExactGraphDefinitionInput<Definition>,
): import('./definition.js').QueryGraph<Definition>

export interface SqlBinding {
  name: string
  parameter: string
  scalarType: import('./definition.js').ScalarType
  index?: number
}

export { batchQuery, batchRelation, composeGraph } from './dsl.js'
