/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QueryGraph {
  get name(): string
  get root(): string
  get sourceCount(): number
  get relationCount(): number
  hasSource(source: string): boolean
  hasField(source: string, field: string): boolean
  hasParameter(parameter: string): boolean
  hasRelation(relation: string): boolean
  selectableFields(): Array<string>
}
export type QueryGraphHandle = QueryGraph

export declare function registerDefinition(definition: unknown): QueryGraph
