/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class QueryGraph {
  get name(): string
  get root(): string
  get sourceCount(): number
  get relationCount(): number
  hasSource(source: string): boolean
  hasField(source: string, field: string): boolean
  hasParameter(parameter: string): boolean
  hasRelation(relation: string): boolean
  selectableFields(): Array<string>
  withRelationalMapping(mapping: import('./definition.js').RelationalMapping): RelationalQueryGraph
}

export declare class RelationalQueryGraph {
  get name(): string
  /**
   * Structural information used by the JavaScript composition facade. This is
   * deliberately separate from the graph-definition wire format.
   */
  get compositionMetadata(): any
  compileSqlServer(operation: import('./definition.js').QueryOperation, options?: import('./definition.js').SqlServerCompileOptions): CompiledSqlStatement
  compileOracle(operation: import('./definition.js').QueryOperation, options?: import('./definition.js').OracleCompileOptions): CompiledSqlStatement
}

export interface CompiledSqlColumn {
  name: string
  path: string
  scalarType: import('./definition.js').ScalarType
  nullable: boolean
  relations: Array<string>
}

export interface CompiledSqlRelation {
  name: string
  from: string
  to: string
  cardinality: import('./definition.js').RelationCardinality
  required: boolean
}

export interface CompiledSqlStatement {
  sql: string
  bindings: Array<SqlBinding>
  columns: Array<CompiledSqlColumn>
  relations: Array<CompiledSqlRelation>
}

export declare function registerDefinition<const Definition extends import('./definition.js').GraphDefinitionInput>(definition: import('./definition.js').ExactGraphDefinitionInput<Definition>): import('./definition.js').QueryGraph<Definition>

export interface SqlBinding {
  name: string
  parameter: string
  scalarType: import('./definition.js').ScalarType
  index?: number
}

export { ComposedQueryGraph, CompiledQueryPlan, batchRelation, composeGraph } from './dsl.js'
